### ISSUE TITLE
Continue upon wrong guess.

### ISSUE THREAD

**Issue by kaanalp28** [Tom-the-Bomb/akinator.py#15]
Idk if I don't know this, but to be able to get the first_guess, it seems like you need to use aki.win(), which seems to end the game.

Is there any way to make it so that it asks if the answer is correct (after 80% progression), if answered with yes, it ends it, if not, it continues from WHERE IT LEFT (NOT restart), and reduces the progression. I want the usual things (The description, Name of the object/animal/character, and a picture of it) to be accessible as the first_guess without finishing the game. Thank you.

If you explain me if theres a method to do it, or if not, if you could add it, I would be very thankful!

Thanks!

**Comment by Tom-the-Bomb** [comment]
Hello,

While the `win()` method may be documented or appear to end the game, it does not. It simply gets akinator to make a guess based on current information, hence you can continue to use the `answer()` method (or any other method you like) after that such as calling the `win()` method again whenever you want. 

The logic you want around asking if the answer is correct or not and whatever else you would like should be just implemented yourself in your application since this is just a wrapper around the API providing a higher level interface for basic akinator functionalities and not a full-blown game interface.

I hope that helps!
Let me know if what I said works out, and if you have any other issues.
